# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast prerecordings 🛋️
docs: true
docsurl: https://radio-aktywne.github.io/emilounge
email: it@radioaktywne.pl
envprefix: EMILOUNGE
events: false
imagename: services/emilounge
importname: emilounge
port: 28000
registry: true
releases: true
reponame: emilounge
repourl: https://github.com/radio-aktywne/emilounge
servicename: emilounge
